from unittest import TestCase
from read_text import read, extract_clues


class TextTest(TestCase):
    LAT_raw = "L. A. Times, Wed, Jan 4, 2023 By Hoang-Kim Vu & Jessica Zetzman / Ed. Patti Varol © 2023 Tribune Content Agency, LLC ACROSS 1Election night graphic 4__ vu 8Noon 14Past 15Stunt legend Knievel 16Padre de tu padre 17Baker's unit 18*Overnight delivery, maybe 20Has wings, say 22\"How groovy\" 23__ Speedwagon 24National Poetry Month 26First-years 29*Injury treated with ice and elevation 32Part of some uniforms 33\"Ella Enchanted\" beast 34Compass pt. 35\"Frozen\" sister 37__ bunt 39Send out 43Part of some uniforms 46Desktop light 49Reddit Q&A session 50*Secret Santa item 53French cake 55The Carpenters' \"We've Only Just __\" 56Mined material 57Chicago team 59Fuzzy fruit or fuzzy birdDOWN62*Meatless meal in a tortilla 66Gere title role 67Nation with a Star of David on its flag 68E-commerce icon 692-Down, in French 70Grammy category 71Hoity-toity type 72Tablet download 1Spice cookie ingredient 269-Across, in Spanish 3Toaster pastry brand 4Family room 5Remains of the day? 6Experts with rings, hoops, and loupes 7Jessica of \"L.A.'s Finest\" 8Leaves high and dry 9Arabic for \"son of\" 10Confer knighthood on 11Honey 12\"Who's Afraid of Virginia Woolf?\" playwright 13Goes back and forth 19__ vez: another time, in Spanish 21Self-care getaway option25__ de Janeiro 27Blesses 28Bauhaus artist Paul 29__/her pronouns 30Chum 31Gave a hand? 36Blue-Emu target 38Geological period with a noted \"explosion\" 40Gist 41Global ﬁnance org.42Skin pic 44Works in a gallery 45Champion on \"Parks and Rec,\" for one 47Baton holder 48Messi's team, familiarly 50Resets, as one's browser history 51Crystal ball gazer 52Soup, in Koreatown53Shoot for the stars 54\"You __ right!\" 58Circle segments 60With 61-Down, \"Get a move on!\" and an instruction for the answers to the starred clues 61See 60-Down 63Snooze 64Buzzworthy creature? 65Wagering site, initially1 2 3   4 5 6 7   8 9 10 11 12 13  14   15   16  17   18 19  20 21   22   23  24 25   26 27 28  29 30 31  32   33   34  35 36   37 38   39 40 41 42  43 44 45   46 47 48   49  50 51 52  53 54   55  56   57 58   59 60 61  62 63 64 65   66  67   68   69  70   71   72 "
    LAT_clues = {'across': [1, 4, 8, 14, 15, 16, 17, 18, 20, 22, 23, 24, 26, 29, 32, 33, 34, 35, 37, 39, 43, 46, 49, 50, 53, 55, 56, 57, 59, 62, 66, 67, 68, 69, 70, 71, 72],
                 'down': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 19, 21, 25, 27, 28, 29, 30, 31, 36, 38, 40, 41, 42, 44, 45, 47, 48, 50, 51, 52, 53, 54, 58, 60, 61, 63, 64, 65]}

    def test_read(self):
        # this is fairly artificial so I'll keep it simple, but I'd want to know if it changed for some reason
        self.assertEqual(self.LAT_raw, read('L. A. Times, Wed, Jan 4, 2023'))

    def test_extract_clues(self):
        expected = {'across': ['Country music sound', 'Coordinating pillowcase', 'Roasting rod', '"Yippee!"', 'Basketball commentator Rebecca', 'Long-haired lap dog, familiarly', 'Change with the times', 'Major composition', 'Working hard', "Smile broadly because of one's own achievement, say", 'Place for a scrub', 'Devoutness', 'Grabbed a bite', 'Chicken __ king', 'Red carpet walker', 'Electric key', "New York City district that's home to the Fearless Girl statue", 'Soup du __', 'Sign of spring', 'Lead-in to Z or Alpha', 'Koalas and emus, in Australia', 'Novelist Atkinson', "Desirable feature of kids' clothing", 'WSW oppositeDOWN', 'Prohibit', 'Rowboat need', 'Cap letters at Busch Stadium', 'Get ready to drive?', 'Mike and __: fruit- flavored candy', 'Amino acid, vis-à-vis protein', 'Aquarium growth', "Void's partner", '"Ta-da!"', 'Thai currency', 'Leave out', '"Black-ish" star Tracee __ Ross', 'East, in Spanish', 'Recedes', 'Pomelo peels'],
                    'down': ['Pan Am rival', 'Roll of dough', 'Literary captain described as a "grand, ungodly, god- like man"', 'Casual rejections', 'Skated by, say', 'React to a yellow light, say', 'Indigenous language in Arizona', 'Touch borders with', "Slam-dancer's place", 'Emergency tire', 'Bite-sized treats whose name means "small ovens" in French', '"Honest!"', 'Spot for un chapeau', "Home brewer's ingredient", 'Domino indent', 'Up and about', 'Some hairy pets', 'Sweet Sixteen winners', 'Alphabetically ﬁrst noble gas', 'Mobile payment app', 'Fighting chance?', 'Director Spike', 'Fair-hiring initials', 'Spree', 'Pay, reluctantly', 'Soccer star and equal-pay advocate Megan', "Donkey's need, in a party game", 'Future flower', 'Overjoy', 'Common lab culture', "Paul Bunyan's blue ox", 'Feeling nothing', 'Smooth-talking', 'Nonkosher sammies', "Potter's oven", 'Jar topper', 'Donkey']}
        self.assertEqual(expected, extract_clues(self.LAT_raw, self.LAT_clues))

        modified_expected = {'across': ['Country music sound for R2-D2', 'Coordinating pillowcase', 'Roasting rod', '"Yippee!"', '1992 Basketball commentator Rebecca', 'Long-haired lap dog, familiarly', 'Change with the times', 'Major 1920 composition', 'Working hard', "Smile broadly because of one's own achievement, say", 'Place for a scrub', 'Devoutness', 'Grabbed a bite', 'Chicken __ king', 'Red carpet walker', 'Electric key', "New York City district that's home to the Fearless Girl statue", 'Soup du __', 'Sign of spring', 'Lead-in to Z or Alpha', 'Koalas and emus, in Australia', 'Novelist Atkinson', "Desirable feature of kids' clothing", 'WSW oppositeDOWN', 'Prohibit', 'Rowboat need', 'Cap letters at Busch Stadium', 'Get ready to drive?', 'Mike and __: fruit- flavored candy', 'Amino acid, vis-à-vis protein', 'Aquarium growth', "Void's partner", '"Ta-da!"', 'Thai currency', 'Leave out', '"Black-ish" star Tracee __ Ross', 'East, in Spanish', 'Recedes', 'Pomelo peels'],
                             'down': ['Pan Am (and C-3PO) rival', 'Roll of dough', 'Literary captain described as a "grand, ungodly, god- like man"', 'Casual rejections', 'Skated by, say', 'React to a yellow light, say', 'Indigenous language in Arizona', 'Touch borders with', "Slam-dancer's place", 'Emergency tire', 'Bite-sized treats whose name means "small ovens" in French', '"Honest!"', 'Spot for un 21st-century chapeau', "Home brewer's ingredient", 'Domino indent', 'Up and about', 'Some hairy pets', 'Sweet Sixteen winners', 'Alphabetically ﬁrst noble gas', 'Mobile payment app', 'Fighting chance?', 'Director Spike', 'Fair-hiring initials', 'Spree', 'Pay, reluctantly', 'Soccer star and equal-pay advocate Megan', "Donkey's need, in a party game", 'Future flower', 'Overjoy', 'Common lab culture', "Paul Bunyan's blue ox", 'Feeling nothing', 'Smooth-talking', 'Nonkosher sammies', "Potter's oven", 'Jar topper', 'Donkey']}
        modified_raw = "1/6/23, 5:40 AM L. A. Times, Tue, Jan 3, 2023 https://cdn4.amuselabs.com/lat/crossword-pdf 1/1L. A. Times, Tue, Jan 3, 2023 By Rebecca Goldstein / Ed. Patti Varol © 2023 Tribune Content Agency, LLC ACROSS 1Country music sound for R2-D2 6Coordinating pillowcase 10Roasting rod 14\"Yippee!\" 151992 Basketball commentator Rebecca 16Long-haired lap dog, familiarly 17Change with the times 18Major 1920 composition 19Working hard 20Smile broadly because of one's own achievement, say 23 Place for a scrub 24Devoutness 25 Grabbed a bite 28 Chicken __ king 30Red carpet walker 31Electric key 33New York City district that's home to the Fearless Girl statue 36Soup du __ 37Sign of spring 38Lead-in to Z or Alpha 39Koalas and emus, in Australia 40Novelist Atkinson 41Desirable feature of kids' clothing 43WSW oppositeDOWN44Prohibit 45Rowboat need 46Cap letters at Busch Stadium 47Get ready to drive? 49Mike and __: fruit- flavored candy 51Amino acid, vis-à-vis protein 56Aquarium growth 57Void's partner 58\"Ta-da!\" 61Thai currency 62Leave out 63\"Black-ish\" star Tracee __ Ross 64East, in Spanish 65Recedes 66Pomelo peels 1Pan Am (and C-3PO) rival 2Roll of dough 3Literary captain described as a \"grand, ungodly, god- like man\" 4Casual rejections 5Skated by, say 6React to a yellow light, say 7Indigenous language in Arizona 8Touch borders with 9Slam-dancer's place 10Emergency tire11Bite-sized treats whose name means \"small ovens\" in French 12\"Honest!\" 13Spot for un 21st-century chapeau 21Home brewer's ingredient 22 Domino indent 25 Up and about 26 Some hairy pets 27Sweet Sixteen winners29 Alphabetically ﬁrst noble gas 30Mobile payment app 32Fighting chance? 34Director Spike 35Fair-hiring initials 36Spree 39Pay, reluctantly 41Soccer star and equal-pay advocate Megan42Donkey's need, in a party game 44Future flower 48Overjoy 50Common lab culture 51Paul Bunyan's blue ox 52Feeling nothing 53Smooth-talking 54Nonkosher sammies 55Potter's oven 59Jar topper 60Donkey1 2 3 4 5   6 7 8 9   10 11 12 13  14   15   16  17   18   19  20 21 22  23   24  25 26 27   28 29   30   31 32  33 34 35   36  37   38   39  40   41 42  43   44   45   46  47 48   49 50  51 52 53 54 55  56   57   58 59 60  61   62   63  64   65   66 "
        self.assertEqual(modified_expected, extract_clues(modified_raw, self.LAT_clues))
        modified_clues = {'across': [n if n != 6 else 7 for n in self.LAT_clues['across']],
                          'down': [n if n != 6 else 7 for n in self.LAT_clues['down']]}
        self.assertIsNone(extract_clues(modified_raw, modified_clues))
        modified_clues = {'across': [n if n != 6 else 7 for n in self.LAT_clues['across']],
                          'down': [n for n in self.LAT_clues['down']]}
        self.assertIsNone(extract_clues(modified_raw, modified_clues))