from unittest import TestCase
from read_text import read, extract_clues


class TextTest(TestCase):
    NYT_raw = "Fred PiscopMarch! Saturday, March 1, 1997 1  2  3  4  5  6  7  8  9  10  11  12 13  14  15 16  17  18 19  20  21  22 23  24  25  26 27  28  29  30  31 32  33  34  35  36  37  38 39  40  41 42  43  44  45  46 47  48  49  50 51  52  53  54 55  56  57  58  59  60 61  62  63  64  65 66  67  68 69  70  71 ACROSS 1Refreshing spots 6Basilica section 10March 7, 1997, e.g.: Abbr. 13Dred __ Decision (event of March 6, 1857) 14\"The Women\" playwright, born March 10 15Othello, for one 16Lend-__ aid, authorized by Congress March 27, 1941 17\"__ go bragh\" (March 17 shout) 18Pond organism 19Hockey great Bobby, born March 20 20\"Now, where __?\" 22Sign of some March births 23Rhine feeder 24Ship in a March 8, 1862 battle 27First man in space, born March 9 31Secrete 32Ashcan  target 33North Carolina college 35See 71-Across 39Prince __ Khan 40Signer of a March 26, 1979 peace treaty 41More, musically 42It was rationed beginning March 29, 1943 44Bad March day for Caesar 45\"Dr.\" born March 2 47Sunday comeback 49Its Independence Day is March 2051\"National war on __\" declared March 16, 1964 54__ Juan Capistrano (noted March return site) 55Bridge expert Charles, born March 4 56Way off 58Tupac's music 61Baltic feeder 62Composer Bartok, born March 25 64Singer Frankie, born March 30 66Beginning-of-Mar ch beast 67Rocker Clapton, born March 30 68Singer John, born March 25 69Prosecutors: Abbr. 70Nair competitor 71With 35-Across, singer born March 26 DOWN 11952 Winter Olympics site 2Whiz on the court 3Fly like an eagle 4U.F.O. pilots 5Sylvester __, a.k.a. Sly Stone, born March 15 6Dart-players' quaffs 7March 23, 1997 festival 8School subj. 9Velvet finish 10Earliest collected edition of Shakespeare 11Chief Justice Taney, born March 17 12Parts of some tax plans, for short15St. Ignatius or St. Agnes 21He followed Jack 22It may be hot or dead 23Motorists' org. founded March 4, 1902 25Reed player 26Sam of Georgia 27Island discovered March 6, 1521 28Up to the task 29Spanish painter born March 30 30Don't have to 34T-shirt size: Abbr. 36Magnum __ 37Spanish ayes 38Persian Empire city 40Casket support 43Place for a brewski 45All tied up 46\"Ich bin __ Berliner\" 48Stags50Dream Team letters 51Conductors' platforms 52Hydrox lookalikes 53Eli 55On March 5, 1933, FDR forbade its export 57Something real 58Actress Tushingham, born March 14 59Before long 60Clinton's first Transportation Secretary, born March 15 62Actor Murphy, born March 6 63Prior to 65Poetic pugilist"
    NYT_clues = {'across': [1,6,10,13,14,15,16,17,18,19,20,22,23,24,27,31,32,33,35,39,40,41,42,44,45,47,49,51,54,55,56,58,61,62,64,66,67,68,69,70,71],
                 'down': [1,2,3,4,5,6,7,8,9,10,11,12,15,21,22,23,25,26,27,28,29,30,34,36,37,38,40,43,45,46,48,50,51,52,53,55,57,58,59,60,62,63,65]}
    LAT_raw = "L. A. Times, Wed, Jan 4, 2023 By Hoang-Kim Vu & Jessica Zetzman / Ed. Patti Varol © 2023 Tribune Content Agency, LLC ACROSS 1Election night graphic 4__ vu 8Noon 14Past 15Stunt legend Knievel 16Padre de tu padre 17Baker's unit 18*Overnight delivery, maybe 20Has wings, say 22\"How groovy\" 23__ Speedwagon 24National Poetry Month 26First-years 29*Injury treated with ice and elevation 32Part of some uniforms 33\"Ella Enchanted\" beast 34Compass pt. 35\"Frozen\" sister 37__ bunt 39Send out 43Part of some uniforms 46Desktop light 49Reddit Q&A session 50*Secret Santa item 53French cake 55The Carpenters' \"We've Only Just __\" 56Mined material 57Chicago team 59Fuzzy fruit or fuzzy birdDOWN62*Meatless meal in a tortilla 66Gere title role 67Nation with a Star of David on its flag 68E-commerce icon 692-Down, in French 70Grammy category 71Hoity-toity type 72Tablet download 1Spice cookie ingredient 269-Across, in Spanish 3Toaster pastry brand 4Family room 5Remains of the day? 6Experts with rings, hoops, and loupes 7Jessica of \"L.A.'s Finest\" 8Leaves high and dry 9Arabic for \"son of\" 10Confer knighthood on 11Honey 12\"Who's Afraid of Virginia Woolf?\" playwright 13Goes back and forth 19__ vez: another time, in Spanish 21Self-care getaway option25__ de Janeiro 27Blesses 28Bauhaus artist Paul 29__/her pronouns 30Chum 31Gave a hand? 36Blue-Emu target 38Geological period with a noted \"explosion\" 40Gist 41Global ﬁnance org.42Skin pic 44Works in a gallery 45Champion on \"Parks and Rec,\" for one 47Baton holder 48Messi's team, familiarly 50Resets, as one's browser history 51Crystal ball gazer 52Soup, in Koreatown53Shoot for the stars 54\"You __ right!\" 58Circle segments 60With 61-Down, \"Get a move on!\" and an instruction for the answers to the starred clues 61See 60-Down 63Snooze 64Buzzworthy creature? 65Wagering site, initially1 2 3   4 5 6 7   8 9 10 11 12 13  14   15   16  17   18 19  20 21   22   23  24 25   26 27 28  29 30 31  32   33   34  35 36   37 38   39 40 41 42  43 44 45   46 47 48   49  50 51 52  53 54   55  56   57 58   59 60 61  62 63 64 65   66  67   68   69  70   71   72 "
    LAT_clues = {'across': [1, 4, 8, 14, 15, 16, 17, 18, 20, 22, 23, 24, 26, 29, 32, 33, 34, 35, 37, 39, 43, 46, 49, 50, 53, 55, 56, 57, 59, 62, 66, 67, 68, 69, 70, 71, 72],
                 'down': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 19, 21, 25, 27, 28, 29, 30, 31, 36, 38, 40, 41, 42, 44, 45, 47, 48, 50, 51, 52, 53, 54, 58, 60, 61, 63, 64, 65]}
    Monday_raw = "Monday Solve a mini puzzle each weekday and remember to come back on Saturday for a special meta puzzle. ACROSS DOWN1 Sphere of activity? 5 Reads someone else's email, maybe 6 Did some fall yardwork 7 Next-to-last word of many fairy tales 8 Like the Marx Brothers or the ﬔree Stooges 1 Cry to a prima donna 2 Clay in a studio 3 On one's guard 4 Vehicle for many a trip in the '60s? 5 Firm cheese?1 2 3 4  5  6  7  8 "
    Monday_clues = {'across':[1,5,6,7,8],
                    'down':[1,2,3,4,5]}

    def test_read(self):
        # this is fairly artificial so I'll keep it simple, but I'd want to know if it changed for some reason
        self.assertEqual(self.LAT_raw, read('L. A. Times, Wed, Jan 4, 2023'))
        self.assertEqual(self.NYT_raw, read('NYT_1997-03-01.pdf'))
        self.assertEqual(self.Monday_raw, read('Monday.pdf'))

    def test_extract_clues(self):
        expected = None
        self.assertEqual(expected, extract_clues(self.Monday_raw, self.Monday_clues))
        expected = {'across':['Refreshing spots','Basilica section', 'March 7, 1997, e.g.: Abbr.', 'Dred __ Decision (event of March 6, 1857)' '"The Women" playwright, born March 10', 'Othello, for one', 'Lend-__ aid, authorized by Congress March 27, 1941', '\"__ go bragh\" (March 17 shout)', 'Pond organism', 'Hockey great Bobby, born March 20', '\"Now, where __?\"', 'Sign of some March births', 'Rhine feeder', 'Ship in a March 8, 1862 battle', 'First man in space, born March 9', 'Secrete', 'Ashcan  target', 'North Carolina college', 'See 71-Across', 'Prince __ Khan', 'Signer of a March 26, 1979 peace treaty', 'More, musically', 'It was rationed beginning March 29, 1943', 'Bad March day for Caesar', '\"Dr.\" born March 2', 'Sunday comeback', 'Its Independence Day is March 20', '\"National war on __\" declared March 16, 1964', '__ Juan Capistrano (noted March return site)', 'Bridge expert Charles, born March 4', 'Way off', 'Tupac\'s music', 'Baltic feeder', 'Composer Bartok, born March 25', 'Singer Frankie, born March 30', 'Beginning-of-Mar ch beast', 'Rocker Clapton, born March 30', 'Singer John, born March 25', 'Prosecutors: Abbr.', 'Nair competitor', 'With 35-Across, singer born March 26'],
                    'down':['Winter Olympics site', 'Whiz on the court', 'Fly like an eagle', 'U.F.O. pilots', 'Sylvester __, a.k.a. Sly Stone, born March 15', 'Dart-players\' quaffs', 'March 23, 1997 festival', 'School subj.', 'Velvet finish', 'Earliest collected edition of Shakespeare', 'Chief Justice Taney, born March 17', 'Parts of some tax plans, for short', 'St. Ignatius or St. Agnes', 'He followed Jack', 'It may be hot or dead', "Motorists' org. founded March 4, 1902", 'Reed player', 'Sam of Georgia', 'Island discovered March 6, 1521', 'Up to the task', 'Spanish painter born March 30', "Don't have to", 'T-shirt size: Abbr.', 'Magnum __', 'Spanish ayes', 'Persian Empire city', 'Casket support', 'Place for a brewski', 'All tied up', '\"Ich bin __ Berliner\"', 'Stags', 'Dream Team letters', "Conductors' platforms", 'Hydrox lookalikes', 'Eli', 'On March 5, 1933, FDR forbade its export', 'Something real', 'Actress Tushingham, born March 14', 'Before long', "Clinton's first Transportation Secretary, born March 15", 'Actor Murphy, born March 6', 'Prior to', 'Poetic pugilist']}
        self.assertEqual(expected, extract_clues(self.NYT_raw, self.NYT_clues))

        expected = {'across': ['Country music sound', 'Coordinating pillowcase', 'Roasting rod', '"Yippee!"', 'Basketball commentator Rebecca', 'Long-haired lap dog, familiarly', 'Change with the times', 'Major composition', 'Working hard', "Smile broadly because of one's own achievement, say", 'Place for a scrub', 'Devoutness', 'Grabbed a bite', 'Chicken __ king', 'Red carpet walker', 'Electric key', "New York City district that's home to the Fearless Girl statue", 'Soup du __', 'Sign of spring', 'Lead-in to Z or Alpha', 'Koalas and emus, in Australia', 'Novelist Atkinson', "Desirable feature of kids' clothing", 'WSW oppositeDOWN', 'Prohibit', 'Rowboat need', 'Cap letters at Busch Stadium', 'Get ready to drive?', 'Mike and __: fruit- flavored candy', 'Amino acid, vis-à-vis protein', 'Aquarium growth', "Void's partner", '"Ta-da!"', 'Thai currency', 'Leave out', '"Black-ish" star Tracee __ Ross', 'East, in Spanish', 'Recedes', 'Pomelo peels'],
                    'down': ['Pan Am rival', 'Roll of dough', 'Literary captain described as a "grand, ungodly, god- like man"', 'Casual rejections', 'Skated by, say', 'React to a yellow light, say', 'Indigenous language in Arizona', 'Touch borders with', "Slam-dancer's place", 'Emergency tire', 'Bite-sized treats whose name means "small ovens" in French', '"Honest!"', 'Spot for un chapeau', "Home brewer's ingredient", 'Domino indent', 'Up and about', 'Some hairy pets', 'Sweet Sixteen winners', 'Alphabetically ﬁrst noble gas', 'Mobile payment app', 'Fighting chance?', 'Director Spike', 'Fair-hiring initials', 'Spree', 'Pay, reluctantly', 'Soccer star and equal-pay advocate Megan', "Donkey's need, in a party game", 'Future flower', 'Overjoy', 'Common lab culture', "Paul Bunyan's blue ox", 'Feeling nothing', 'Smooth-talking', 'Nonkosher sammies', "Potter's oven", 'Jar topper', 'Donkey']}
        self.assertEqual(expected, extract_clues(self.LAT_raw, self.LAT_clues))

        modified_expected = {'across': ['Country music sound for R2-D2', 'Coordinating pillowcase', 'Roasting rod', '"Yippee!"', '1992 Basketball commentator Rebecca', 'Long-haired lap dog, familiarly', 'Change with the times', 'Major 1920 composition', 'Working hard', "Smile broadly because of one's own achievement, say", 'Place for a scrub', 'Devoutness', 'Grabbed a bite', 'Chicken __ king', 'Red carpet walker', 'Electric key', "New York City district that's home to the Fearless Girl statue", 'Soup du __', 'Sign of spring', 'Lead-in to Z or Alpha', 'Koalas and emus, in Australia', 'Novelist Atkinson', "Desirable feature of kids' clothing", 'WSW oppositeDOWN', 'Prohibit', 'Rowboat need', 'Cap letters at Busch Stadium', 'Get ready to drive?', 'Mike and __: fruit- flavored candy', 'Amino acid, vis-à-vis protein', 'Aquarium growth', "Void's partner", '"Ta-da!"', 'Thai currency', 'Leave out', '"Black-ish" star Tracee __ Ross', 'East, in Spanish', 'Recedes', 'Pomelo peels'],
                             'down': ['Pan Am (and C-3PO) rival', 'Roll of dough', 'Literary captain described as a "grand, ungodly, god- like man"', 'Casual rejections', 'Skated by, say', 'React to a yellow light, say', 'Indigenous language in Arizona', 'Touch borders with', "Slam-dancer's place", 'Emergency tire', 'Bite-sized treats whose name means "small ovens" in French', '"Honest!"', 'Spot for un 21st-century chapeau', "Home brewer's ingredient", 'Domino indent', 'Up and about', 'Some hairy pets', 'Sweet Sixteen winners', 'Alphabetically ﬁrst noble gas', 'Mobile payment app', 'Fighting chance?', 'Director Spike', 'Fair-hiring initials', 'Spree', 'Pay, reluctantly', 'Soccer star and equal-pay advocate Megan', "Donkey's need, in a party game", 'Future flower', 'Overjoy', 'Common lab culture', "Paul Bunyan's blue ox", 'Feeling nothing', 'Smooth-talking', 'Nonkosher sammies', "Potter's oven", 'Jar topper', 'Donkey']}
        modified_raw = "1/6/23, 5:40 AM L. A. Times, Tue, Jan 3, 2023 https://cdn4.amuselabs.com/lat/crossword-pdf 1/1L. A. Times, Tue, Jan 3, 2023 By Rebecca Goldstein / Ed. Patti Varol © 2023 Tribune Content Agency, LLC ACROSS 1Country music sound for R2-D2 6Coordinating pillowcase 10Roasting rod 14\"Yippee!\" 151992 Basketball commentator Rebecca 16Long-haired lap dog, familiarly 17Change with the times 18Major 1920 composition 19Working hard 20Smile broadly because of one's own achievement, say 23 Place for a scrub 24Devoutness 25 Grabbed a bite 28 Chicken __ king 30Red carpet walker 31Electric key 33New York City district that's home to the Fearless Girl statue 36Soup du __ 37Sign of spring 38Lead-in to Z or Alpha 39Koalas and emus, in Australia 40Novelist Atkinson 41Desirable feature of kids' clothing 43WSW oppositeDOWN44Prohibit 45Rowboat need 46Cap letters at Busch Stadium 47Get ready to drive? 49Mike and __: fruit- flavored candy 51Amino acid, vis-à-vis protein 56Aquarium growth 57Void's partner 58\"Ta-da!\" 61Thai currency 62Leave out 63\"Black-ish\" star Tracee __ Ross 64East, in Spanish 65Recedes 66Pomelo peels 1Pan Am (and C-3PO) rival 2Roll of dough 3Literary captain described as a \"grand, ungodly, god- like man\" 4Casual rejections 5Skated by, say 6React to a yellow light, say 7Indigenous language in Arizona 8Touch borders with 9Slam-dancer's place 10Emergency tire11Bite-sized treats whose name means \"small ovens\" in French 12\"Honest!\" 13Spot for un 21st-century chapeau 21Home brewer's ingredient 22 Domino indent 25 Up and about 26 Some hairy pets 27Sweet Sixteen winners29 Alphabetically ﬁrst noble gas 30Mobile payment app 32Fighting chance? 34Director Spike 35Fair-hiring initials 36Spree 39Pay, reluctantly 41Soccer star and equal-pay advocate Megan42Donkey's need, in a party game 44Future flower 48Overjoy 50Common lab culture 51Paul Bunyan's blue ox 52Feeling nothing 53Smooth-talking 54Nonkosher sammies 55Potter's oven 59Jar topper 60Donkey1 2 3 4 5   6 7 8 9   10 11 12 13  14   15   16  17   18   19  20 21 22  23   24  25 26 27   28 29   30   31 32  33 34 35   36  37   38   39  40   41 42  43   44   45   46  47 48   49 50  51 52 53 54 55  56   57   58 59 60  61   62   63  64   65   66 "
        self.assertEqual(modified_expected, extract_clues(modified_raw, self.LAT_clues))
        modified_clues = {'across': [n if n != 6 else 7 for n in self.LAT_clues['across']],
                          'down': [n if n != 6 else 7 for n in self.LAT_clues['down']]}
        self.assertIsNone(extract_clues(modified_raw, modified_clues))
        modified_clues = {'across': [n if n != 6 else 7 for n in self.LAT_clues['across']],
                          'down': [n for n in self.LAT_clues['down']]}
        self.assertIsNone(extract_clues(modified_raw, modified_clues))